title: "AB-3"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

#repository: "se-edu/addressbook-level3"
repository: "AY2425S1-CS2103T-T12-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
